### ISSUE TITLE
Allow multiple ingress objects

### ISSUE THREAD

**Issue by criskurtin** [SysbeeTech/kubedeploy#23]
Currently only single `ingress` object can be defined without using the `extraObjects` field and defining raw manifests. `ingress` field should be an array instead, in order to natively support defining multiple ingresses.

## Expected Behavior

```yaml
ingress:
  - enabled: true
    className: "haproxy-public"
    hosts:
      - host: api.example.com
        paths:
          - path: /
    tls:
      - secretName: api
        hosts:
          - api.example.com
  - enabled: true
    hosts:
      - host: api-internal.example.com
        paths:
          - path: /
    tls:
      - secretName: api-internal
        hosts:
          - api-internal.example.com
```

Result of this configuration should be two ingress manifests.

## Current Behavior

Currently, the `ingress` field does not support specifying an array of objects. Only single ingress object can be specified instead:

```yaml
ingress:
  enabled: true
  hosts:
    - host: api-internal.example.com
      paths:
        - path: /
  tls:
    - secretName: api-internal
      hosts:
        - api-internal.example.com
```

## Possible Solution

`ingress.yaml` template should iterate through specified array elements and use the already implemented templating logic to generate individual ingress manifests. Sort of a combination between `extra-objects.yaml` with `range` function and the existing `ingress.yaml` template.

## Context

This would be useful if multiple ingresses should be defined. For example, most of the service endpoints might only be available to the internal network (using the `haproxy` default ingress controller), while the endpoints prefixed with `/public` might need to be exposed through the `haproxy-public` ingress controller. At the moment, the solution is a bit clumsy and requires specifying one of the above as a raw manifest.

## Your Environment

- Chart version used: 1.1.1
