### ISSUE TITLE
Add podSpread

### ISSUE THREAD

**Issue by btoic** [SysbeeTech/kubedeploy#34]
Similar to [podAntiAffinity](https://kubedeploy.app/start/values/podantiaffinity.html) feature, create easier to configure podTopologyConstraints via  **podSpread** value option.

Example usage:

```yaml
podSpread:
  type: soft # or hard (default "" which disables it)
  skew: 1 # optional (default 1)
  minDomains: 2 # optional (default none)
  key: kubernetes.io/hostname # optional (default hostname)
```

This should define a simple pod topology constraints based on chart labels and default values from above.
type **soft** should map to `whenUnsatisfiable: ScheduleAnyway` while **hard** should map to `whenUnsatisfiable: DoNotSchedule`

At the end minimal configuration can then look like:

```yaml
podSpread:
  type: soft
```

If podToplologyConstraint values are defined they should override any **podSpread** options
