### ISSUE TITLE
avoidNodeLabels

### ISSUE THREAD

**Issue by btoic** [SysbeeTech/kubedeploy#35]
Add value configuration for avoiding nodes with specific lables, in essence option to acheve oposite effect  to nodeSelector.

Example use case with current setup:

```yaml
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: eks.amazonaws.com/compute-type
              operator: NotIn
              values:
                - fargate
```

Should be possible to reduce reduce to:

```yaml
avoidNodeLabels:
  eks.amazonaws.com/compute-type: fargate
```
