### ISSUE TITLE
optional healthcheck probes

### ISSUE THREAD

**Issue by btoic** [SysbeeTech/kubedeploy#7]
When defining values for healthcheck probes, allow for the probes to be optional.

## Expected Behavior

When defining values like:
```yaml
healthcheck:
  enabled: true
  probes:
    livenessProbe:
      tcpSocket:
        port: http
```

Chart should only define livenessProbe in  container spec.

## Current Behavior

With the example above, chart is rendering all three probes defined in default values. Other rendered probes end up without required handler type, making the deployments fail.

## Possible Solution

1. Remove probe empty maps from default values for all containers. Will require more info in the docs
2. create a helper function for healthchecks that can be used for all containers, iterating over the values and deploying only non empty probe maps

## Steps to Reproduce (for bugs)

See the example values above

## Your Environment

- Chart version used: 1.1.0
